#include "build_info.h"

// Generated by SConstruct on every build, rewritten only when it changes.
#include "build_info.gen.h"

namespace godot_git {

const char *build_version() {
	return GODOT_GIT_BUILD_VERSION;
}

const char *build_commit() {
	return GODOT_GIT_BUILD_COMMIT;
}

const char *build_url() {
	return GODOT_GIT_BUILD_URL;
}

} // namespace godot_git
